#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "$0 [FILE] KEY"
    echo "copies the value associated with KEY from FILE file to pasteboard"
    echo "FILE defaults to \$KHALED_DEFAULT_FILE"
    exit
  elif [ $# -eq 1 ]
    then
      FILE=$KHALED_DEFAULT_FILE
      NAME=$1
  elif [ $# -eq 2 ]
    then
      FILE=$1
      NAME=$2
fi

if [ ! -f $FILE ]; then
    echo "file '$FILE' not found"
    exit
fi

(
  openssl enc -aes-256-cbc -d -in $FILE | grep $NAME | sed 's/^[^ ]* //g' | tr -d '[:space:]' | pbcopy
) && echo "ok"
