#!/bin/bash
if [ $# -eq 0 ]
  then
    echo "$0 FILE"
    echo "lists keys in FILE"
    exit
fi

FILE=$1

if [ ! -f $FILE ]; then
    echo "file '$FILE' not found"
    exit
fi

openssl enc -aes-256-cbc -d -in $FILE | sed 's/ [^ ]*$//g'
